* 2023
This directory contains some attempts at solutions to the 2023 Advent of Code
problems. I chose Janet (v1.32.1) as my language of choice; I later switched to
Go.

** Why Janet?
I don't yet know the language, but it has some appealing properties.

- It can be compiled and distributed.
- It has a minimal startup time.
- It can be embedded.
- It's small.
- It's ergonomic (e.g., it comes with threading macros).
- It has built-in support for parsing expression grammars.
- Some lovely people created [[https://github.com/andrewchambers/janetsh][sh]] and [[https://github.com/ianthehenry/cmd][cmd]].

It has the potential to displace my use of Bash and Ruby, but it's only through
use that this can be determined.

I'll update this when I feel I'm done with this experiment.

** Conclusions
I chose to switch to Go, my working language, when working on day 5.

I like the compactness of Janet, I like the left-to-right style that threading
macros provide, I like being able to place my tests next to my code with [[https://github.com/ianthehenry/judge][judge]],
and parsing expression grammars are revelatory---but a language's usefulness is
limited by its tooling and its documentation. These are lacking in Janet, at
least for now.

It's also confirmed that I'm intolerant of the kinds of errors that dynamic
typing produces.
